import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

/**
 * The reference clip is 3.2s and holds the rewritten line for its last fifth of
 * a second. 102 frames is that plus a beat, so the deselect lands and the new
 * claim sits long enough to read before the composition ends.
 */
export const textRewriteConfig: ComponentConfig = {
  componentName: "TextRewrite",
  importPath: "@/components/snap-cn/text-rewrite",
  controls: {
    headline: {
      type: "text",
      default: "Or just add snapcn",
      label: "Headline",
    },
    keep: {
      type: "number",
      default: 1,
      min: 0,
      max: 8,
      step: 1,
      label: "Words kept",
    },
    append: { type: "text", default: "registry", label: "Written on" },
    wordAt: {
      type: "number",
      default: 0.217,
      min: 0,
      max: 2,
      step: 0.005,
      label: "First word at (s)",
    },
    wordStagger: {
      type: "number",
      default: 0.189,
      min: 0.02,
      max: 0.8,
      step: 0.002,
      label: "Word stagger (s)",
    },
    wordDuration: {
      type: "number",
      default: 0.085,
      min: 0.02,
      max: 1,
      step: 0.005,
      label: "Word opens in (s)",
    },
    coolDelay: {
      type: "number",
      default: 0.189,
      min: 0,
      max: 1.5,
      step: 0.005,
      label: "Accent holds (s)",
    },
    coolDuration: {
      type: "number",
      default: 0.189,
      min: 0.01,
      max: 1.5,
      step: 0.005,
      label: "Accent cools over (s)",
    },
    cutAt: {
      type: "number",
      default: 1.033,
      min: 0.1,
      max: 6,
      step: 0.01,
      label: "Comes forward at (s)",
    },
    zoomDuration: {
      type: "number",
      default: 0,
      min: 0,
      max: 2,
      step: 0.01,
      label: "Forward over (s)",
    },
    zoom: {
      type: "number",
      default: 2.41,
      min: 1,
      max: 6,
      step: 0.01,
      label: "Forward to",
    },
    dragAt: {
      type: "number",
      default: 1.033,
      min: 0.1,
      max: 6,
      step: 0.005,
      label: "Select at (s)",
    },
    dragDuration: {
      type: "number",
      default: 0.2,
      min: 0.02,
      max: 2,
      step: 0.005,
      label: "Drag over (s)",
    },
    eraseAt: {
      type: "number",
      default: 1.45,
      min: 0.1,
      max: 8,
      step: 0.005,
      label: "Erase at (s)",
    },
    eraseDuration: {
      type: "number",
      default: 0.517,
      min: 0.05,
      max: 3,
      step: 0.005,
      label: "Erase over (s)",
    },
    rewriteAt: {
      type: "number",
      default: 2,
      min: 0.1,
      max: 8,
      step: 0.005,
      label: "Rewrite at (s)",
    },
    rewriteDuration: {
      type: "number",
      default: 0.533,
      min: 0.05,
      max: 3,
      step: 0.005,
      label: "Rewrite over (s)",
    },
    deselectAt: {
      type: "number",
      default: 2.85,
      min: 0.1,
      max: 10,
      step: 0.005,
      label: "Deselect at (s)",
    },
    deselectDuration: {
      type: "number",
      default: 0.15,
      min: 0.02,
      max: 2,
      step: 0.005,
      label: "Deselect over (s)",
    },
    fontSize: {
      type: "number",
      default: 20,
      min: 8,
      max: 64,
      step: 0.5,
      label: "Type size",
    },
    fontWeight: {
      type: "number",
      default: 500,
      min: 400,
      max: 600,
      step: 100,
      label: "Weight",
    },
    centerY: {
      type: "number",
      default: 0.4902,
      min: 0.1,
      max: 0.9,
      step: 0.002,
      label: "Line Y",
    },
    selectionOpacity: {
      type: "number",
      default: 0.21,
      min: 0,
      max: 0.8,
      step: 0.005,
      label: "Selection strength",
    },
    selectionAngle: {
      type: "number",
      default: 90,
      min: 0,
      max: 180,
      step: 1,
      label: "Sheen angle",
    },
    markSize: {
      type: "number",
      default: 1.15,
      min: 0,
      max: 3,
      step: 0.01,
      label: "Mark size (em)",
    },
    glow: { type: "boolean", default: true, label: "Wash" },
    glowOpacity: {
      type: "number",
      default: 0.075,
      min: 0,
      max: 0.5,
      step: 0.005,
      label: "Wash strength",
    },
    accentColor: {
      type: "color",
      default: "#3072db",
      label: "Accent",
      brand: "accent",
    },
    mode: {
      type: "select",
      default: "light",
      options: ["light", "dark"],
      label: "Mode",
    },
  },
  // `speed` is appended from SHARED_CONTROLS in registry/__index__.tsx.
  durationInFrames: 102,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
};
