import {
  type ComponentConfig,
  FONT_FAMILY_CONTROL,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const textRevealConfig: ComponentConfig = {
  componentName: "TextReveal",
  importPath: "@/components/snap-cn/text-reveal",
  controls: {
    text: { type: "text", default: "Meet Acme Billing", label: "Text" },
    fontSize: {
      type: "number",
      default: 72,
      min: 12,
      max: 160,
      step: 1,
      label: "Font size",
    },
    color: { type: "color", default: "#101828", label: "Color" },
    fontWeight: {
      type: "select",
      default: "600",
      options: FONT_WEIGHT_OPTIONS,
      label: "Font weight",
    },
    initialScale: {
      type: "number",
      default: 2.3,
      min: 1,
      max: 4,
      step: 0.1,
      label: "Lead word scale",
    },
    pushScale: {
      type: "number",
      default: 1.06,
      min: 1,
      max: 1.3,
      step: 0.01,
      label: "Forward push",
    },
    introDuration: {
      type: "number",
      default: 6,
      min: 0,
      max: 30,
      step: 1,
      label: "Intro fade",
    },
    holdDuration: {
      type: "number",
      default: 12,
      min: 0,
      max: 40,
      step: 1,
      label: "Hold (frames)",
    },
    recedeDuration: {
      type: "number",
      default: 14,
      min: 4,
      max: 60,
      step: 1,
      label: "Recede duration",
    },
    assembleDuration: {
      type: "number",
      default: 30,
      min: 8,
      max: 120,
      step: 1,
      label: "Assemble duration",
    },
    wordDelay: {
      type: "number",
      default: 7,
      min: 0,
      max: 40,
      step: 1,
      label: "Word delay",
    },
    wordStagger: {
      type: "number",
      default: 4,
      min: 0,
      max: 20,
      step: 1,
      label: "Word stagger",
    },
    wordDuration: {
      type: "number",
      default: 14,
      min: 4,
      max: 60,
      step: 1,
      label: "Word push duration",
    },
    wordPush: {
      type: "number",
      default: 0.5,
      min: 0,
      max: 2,
      step: 0.05,
      label: "Word push distance (em)",
    },
    wordFade: {
      type: "number",
      default: 2,
      min: 0,
      max: 20,
      step: 1,
      label: "Word fade",
    },
    fontFamily: FONT_FAMILY_CONTROL,
  },
  durationInFrames: 90,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#FAFAFA" },
};
