import {
  type ComponentConfig,
  FONT_FAMILY_CONTROL,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const laptopFrameConfig: ComponentConfig = {
  componentName: "LaptopFrame",
  importPath: "@/components/snap-cn/laptop-frame",
  controls: {
    screenSrc: {
      type: "image",
      default: "/demos/answer-stream.mp4",
      label: "Screen (image or video)",
    },
    entrance: {
      type: "select",
      default: "open",
      options: ["rise", "open", "none"],
      label: "Entrance",
    },
    finale: {
      type: "select",
      default: "zoom-to-screen",
      options: ["none", "zoom-to-screen"],
      label: "Finale",
    },
    notchLabel: {
      type: "text",
      default: "AirPods Connected",
      label: "Notch label",
    },
    showNotch: { type: "boolean", default: true, label: "Notch" },
    batteryLevel: {
      type: "number",
      default: 85,
      min: 0,
      max: 100,
      step: 1,
      label: "Battery level",
    },
    bezelColor: { type: "color", default: "#1D1D1F", label: "Bezel color" },
    screenColor: { type: "color", default: "#FFFFFF", label: "Screen color" },
    restTilt: {
      type: "number",
      default: 18,
      min: 0,
      max: 45,
      step: 1,
      label: "Lid tilt",
    },
    radius: {
      type: "number",
      default: 22,
      min: 8,
      max: 40,
      step: 1,
      label: "Lid radius",
    },
    scale: {
      type: "number",
      default: 0.85,
      min: 0.4,
      max: 1.4,
      step: 0.05,
      label: "Scale",
    },
    floatLoop: { type: "boolean", default: true, label: "Float loop" },
    floatAmplitude: {
      type: "number",
      default: 4,
      min: 0,
      max: 16,
      step: 1,
      label: "Float amplitude",
    },
    shadow: {
      type: "text",
      default: "0 40px 80px rgba(10,12,20,0.45)",
      label: "Shadow",
    },
    fontFamily: FONT_FAMILY_CONTROL,
  },
  durationInFrames: 240,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#000000" },
};
