import {
  type ComponentConfig,
  FONT_FAMILY_CONTROL,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const textSwellConfig: ComponentConfig = {
  componentName: "TextSwell",
  importPath: "@/components/snap-cn/text-swell",
  controls: {
    text: { type: "text", default: "No extra charge", label: "Text" },
    fontSize: {
      type: "number",
      default: 72,
      min: 12,
      max: 160,
      step: 1,
      label: "Font size",
    },
    color: { type: "color", default: "#101828", label: "Color" },
    fontWeight: {
      type: "select",
      default: "600",
      options: FONT_WEIGHT_OPTIONS,
      label: "Font weight",
    },
    riseDistance: {
      type: "number",
      default: 0.7,
      min: 0,
      max: 3,
      step: 0.05,
      label: "Rise from below (em)",
    },
    riseDuration: {
      type: "number",
      default: 10,
      min: 1,
      max: 60,
      step: 1,
      label: "Rise duration",
    },
    introDuration: {
      type: "number",
      default: 8,
      min: 0,
      max: 30,
      step: 1,
      label: "Intro fade",
    },
    frontScale: {
      type: "number",
      default: 2.1,
      min: 1,
      max: 4,
      step: 0.1,
      label: "Front scale",
    },
    approachDelay: {
      type: "number",
      default: 14,
      min: 0,
      max: 60,
      step: 1,
      label: "Approach delay",
    },
    approachDuration: {
      type: "number",
      default: 20,
      min: 4,
      max: 80,
      step: 1,
      label: "Approach",
    },
    wordDelay: {
      type: "number",
      default: 27,
      min: 0,
      max: 80,
      step: 1,
      label: "Word delay",
    },
    wordStagger: {
      type: "number",
      default: 14,
      min: 1,
      max: 40,
      step: 1,
      label: "Word stagger",
    },
    wordPush: {
      type: "number",
      default: 0.15,
      min: 0,
      max: 1,
      step: 0.05,
      label: "Word push (em)",
    },
    wordPushDuration: {
      type: "number",
      default: 12,
      min: 2,
      max: 40,
      step: 1,
      label: "Word push / shove",
    },
    bounceWords: {
      type: "number",
      default: 1,
      min: 0,
      max: 6,
      step: 1,
      label: "Words that bounce",
    },
    letterSwell: {
      type: "number",
      default: 0.23,
      min: 0,
      max: 1,
      step: 0.01,
      label: "Letter swell",
    },
    letterStagger: {
      type: "number",
      default: 2,
      min: 0.5,
      max: 12,
      step: 0.5,
      label: "Letter stagger",
    },
    letterRise: {
      type: "number",
      default: 3,
      min: 1,
      max: 20,
      step: 1,
      label: "Letter rise",
    },
    letterHold: {
      type: "number",
      default: 0,
      min: 0,
      max: 30,
      step: 1,
      label: "Letter hold",
    },
    letterFall: {
      type: "number",
      default: 6,
      min: 1,
      max: 30,
      step: 1,
      label: "Letter fall",
    },
    holdDuration: {
      type: "number",
      default: 6,
      min: 0,
      max: 60,
      step: 1,
      label: "Front hold",
    },
    recedeDuration: {
      type: "number",
      default: 18,
      min: 4,
      max: 80,
      step: 1,
      label: "Recede",
    },
    fontFamily: FONT_FAMILY_CONTROL,
  },
  durationInFrames: 110,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#FAFAFA" },
};
