import {
  type ComponentConfig,
  FONT_FAMILY_CONTROL,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const orbitGalleryConfig: ComponentConfig = {
  componentName: "OrbitGallery",
  importPath: "@/components/snap-cn/orbit-gallery",
  controls: {
    title: {
      type: "text",
      default: "A whole new universe",
      label: "Title",
    },
    subtitle: {
      type: "text",
      default: "Article — The Design Process",
      label: "Subtitle",
    },
    buttonLabel: {
      type: "text",
      default: "Explore",
      label: "Button label",
    },
    turns: {
      type: "number-input",
      default: 3,
      min: 1,
      max: 6,
      step: 0.1,
      label: "Spiral coils",
    },
    spacing: {
      type: "number-input",
      default: 5,
      min: 2,
      max: 14,
      step: 0.5,
      label: "Card spacing",
    },
    spread: {
      type: "number-input",
      default: 7,
      min: 1,
      max: 10,
      step: 0.5,
      label: "Spread",
    },
    imageSize: {
      type: "number-input",
      default: 172,
      min: 80,
      max: 360,
      step: 10,
      label: "Image size",
    },
    sizeAttenuation: {
      type: "number-input",
      default: 2,
      min: 0,
      max: 4,
      step: 0.25,
      label: "Center shrink",
    },
    cornerRadius: {
      type: "number-input",
      default: 5,
      min: 0,
      max: 20,
      step: 1,
      label: "Corner radius",
    },
    orbitSeconds: {
      type: "number-input",
      default: 40,
      min: 10,
      max: 120,
      step: 1,
      label: "Seconds per flow",
    },
    background: { type: "color", default: "#050505", label: "Background" },
    textColor: { type: "color", default: "#FFFFFF", label: "Text color" },
    fontFamily: FONT_FAMILY_CONTROL,
  },
  durationInFrames: 300,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#050505" },
};
