import {
  type ComponentConfig,
  FONT_FAMILY_CONTROL,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const wordFlipConfig: ComponentConfig = {
  componentName: "WordFlip",
  importPath: "@/components/snap-cn/word-flip",
  controls: {
    prefix: { type: "text", default: "Looking For A", label: "Prefix" },
    suffix: { type: "text", default: "Portfolio", label: "Suffix" },
    cps: {
      type: "number",
      default: 9,
      min: 3,
      max: 24,
      step: 0.5,
      label: "Typing speed (cps)",
    },
    pause: {
      type: "number",
      default: 6,
      min: 0,
      max: 40,
      step: 1,
      label: "Pause",
    },
    cycle: {
      type: "number",
      default: 35,
      min: 16,
      max: 90,
      step: 1,
      label: "Cycle",
    },
    exitDuration: {
      type: "number",
      default: 9,
      min: 4,
      max: 24,
      step: 1,
      label: "Exit duration",
    },
    enterDuration: {
      type: "number",
      default: 9,
      min: 4,
      max: 24,
      step: 1,
      label: "Enter duration",
    },
    overlap: {
      type: "number",
      default: 3,
      min: 0,
      max: 8,
      step: 1,
      label: "Overlap",
    },
    perspective: {
      type: "number",
      default: 6.5,
      min: 2,
      max: 20,
      step: 0.5,
      label: "Perspective (em)",
    },
    caret: { type: "boolean", default: true, label: "Caret" },
    fontSize: {
      type: "number",
      default: 72,
      min: 12,
      max: 120,
      step: 1,
      label: "Font size",
    },
    color: { type: "color", default: "#101828", label: "Color" },
    fontWeight: {
      type: "select",
      default: "600",
      options: FONT_WEIGHT_OPTIONS,
      label: "Font weight",
    },
    fontFamily: FONT_FAMILY_CONTROL,
  },
  durationInFrames: 180,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#FAFAFA" },
};
