import {
  type ComponentConfig,
  FONT_FAMILY_CONTROL,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

/**
 * The reference clip is 1.88s. The push forward is a ramp here rather than the
 * recording's cut (see the note on `zoomScale`), which moves the drag later, so
 * 72 frames is what it takes for the selection to land and sit long enough to
 * read before the composition ends.
 */
export const textSelectConfig: ComponentConfig = {
  componentName: "TextSelect",
  importPath: "@/components/snap-cn/text-select",
  controls: {
    headline: {
      type: "text",
      default: "One command into your project.",
      label: "Headline",
    },
    wordAt: {
      type: "number",
      default: 0.066,
      min: 0,
      max: 2,
      step: 0.005,
      label: "First word at (s)",
    },
    wordStagger: {
      type: "number",
      default: 0.208,
      min: 0.02,
      max: 0.8,
      step: 0.002,
      label: "Word stagger (s)",
    },
    wordDuration: {
      type: "number",
      default: 0.13,
      min: 0.02,
      max: 1,
      step: 0.005,
      label: "Word lands in (s)",
    },
    shiftX: {
      type: "number",
      default: 0.475,
      min: -2,
      max: 2,
      step: 0.005,
      label: "Line arrives from (em)",
    },
    coolDelay: {
      type: "number",
      default: 0.208,
      min: 0,
      max: 1.5,
      step: 0.005,
      label: "Accent holds (s)",
    },
    coolDuration: {
      type: "number",
      default: 0.208,
      min: 0.01,
      max: 1.5,
      step: 0.005,
      label: "Accent cools over (s)",
    },
    cutAt: {
      type: "number",
      default: 1.13,
      min: 0.1,
      max: 6,
      step: 0.01,
      label: "Comes forward at (s)",
    },
    zoomDuration: {
      type: "number",
      default: 0.42,
      min: 0,
      max: 2,
      step: 0.01,
      label: "Forward over (s)",
    },
    zoom: {
      type: "number",
      default: 2.39,
      min: 1,
      max: 6,
      step: 0.01,
      label: "Forward to",
    },
    selectAt: {
      type: "number",
      default: 1.4,
      min: 0.1,
      max: 6,
      step: 0.005,
      label: "Select at (s)",
    },
    selectDuration: {
      type: "number",
      default: 0.26,
      min: 0.02,
      max: 2,
      step: 0.005,
      label: "Drag over (s)",
    },
    fontSize: {
      type: "number",
      default: 20,
      min: 8,
      max: 64,
      step: 0.5,
      label: "Type size",
    },
    fontWeight: {
      type: "number",
      default: 500,
      min: 400,
      max: 600,
      step: 100,
      label: "Weight",
    },
    centerY: {
      type: "number",
      default: 0.5116,
      min: 0.1,
      max: 0.9,
      step: 0.002,
      label: "Line Y",
    },
    selectionOpacity: {
      type: "number",
      default: 0.207,
      min: 0,
      max: 0.8,
      step: 0.005,
      label: "Selection strength",
    },
    selectionAngle: {
      type: "number",
      default: 90,
      min: 0,
      max: 180,
      step: 1,
      label: "Sheen angle",
    },
    shineColor: { type: "color", default: "#ffffff", label: "Glint" },
    shineOpacity: {
      type: "number",
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.01,
      label: "Glint strength",
    },
    shineDepth: {
      type: "number",
      default: 0.55,
      min: 0,
      max: 2,
      step: 0.01,
      label: "Glint shoulders",
    },
    shineWidth: {
      type: "number",
      default: 0.3,
      min: 0.05,
      max: 1,
      step: 0.01,
      label: "Glint width",
    },
    shineDuration: {
      type: "number",
      default: 0.62,
      min: 0.05,
      max: 3,
      step: 0.01,
      label: "Glint crosses in (s)",
    },
    shineEvery: {
      type: "number",
      default: 1.1,
      min: 0,
      max: 6,
      step: 0.05,
      label: "Glint every (s)",
    },
    selectionPad: {
      type: "number",
      default: 0.063,
      min: 0,
      max: 1,
      step: 0.005,
      label: "Selection pad (em)",
    },
    glow: { type: "boolean", default: true, label: "Wash" },
    glowOpacity: {
      type: "number",
      default: 0.075,
      min: 0,
      max: 0.5,
      step: 0.005,
      label: "Wash strength",
    },
    accentColor: {
      type: "color",
      default: "#3072db",
      label: "Accent",
      brand: "accent",
    },
    mode: {
      type: "select",
      default: "light",
      options: ["light", "dark"],
      label: "Mode",
    },
    fontFamily: FONT_FAMILY_CONTROL,
  },
  // `speed` is appended from SHARED_CONTROLS in registry/__index__.tsx.
  durationInFrames: 72,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
};
