import {
  type ComponentConfig,
  FONT_FAMILY_CONTROL,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const textSwapConfig: ComponentConfig = {
  componentName: "TextSwap",
  importPath: "@/components/snap-cn/text-swap",
  controls: {
    fromText: {
      type: "text",
      default: "Manual invoicing",
      label: "From text",
    },
    toText: {
      type: "text",
      default: "Automated with Acme",
      label: "To text",
    },
    transition: {
      type: "select",
      default: "fly-through",
      options: [
        "fly-through",
        "fade-through",
        "crossfade",
        "shared-axis-y",
        "shared-axis-z",
        "cut",
      ],
      label: "Transition",
    },
    unit: {
      type: "select",
      default: "block",
      options: ["block", "word"],
      label: "Unit",
    },
    exitDuration: {
      type: "number",
      default: 20,
      min: 2,
      max: 40,
      step: 1,
      label: "Exit duration",
    },
    enterDuration: {
      type: "number",
      default: 16,
      min: 2,
      max: 40,
      step: 1,
      label: "Enter duration",
    },
    exitStagger: {
      type: "number",
      default: 1,
      min: 0,
      max: 8,
      step: 1,
      label: "Exit stagger",
    },
    enterStagger: {
      type: "number",
      default: 2,
      min: 0,
      max: 8,
      step: 1,
      label: "Enter stagger",
    },
    overlap: {
      type: "number",
      default: 1,
      min: 0,
      max: 12,
      step: 1,
      label: "Overlap",
    },
    microDelay: {
      type: "number",
      default: 2,
      min: 0,
      max: 12,
      step: 1,
      label: "Micro delay",
    },
    fontSize: {
      type: "number",
      default: 72,
      min: 12,
      max: 160,
      step: 1,
      label: "Font size",
    },
    color: { type: "color", default: "#101828", label: "Color" },
    fontWeight: {
      type: "select",
      default: "600",
      options: FONT_WEIGHT_OPTIONS,
      label: "Font weight",
    },
    fontFamily: FONT_FAMILY_CONTROL,
  },
  durationInFrames: 90,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#ffffff" },
};
