import {
  type ComponentConfig,
  FONT_FAMILY_CONTROL,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const textBuildConfig: ComponentConfig = {
  componentName: "TextBuild",
  importPath: "@/components/snap-cn/text-build",
  controls: {
    text: {
      type: "text",
      default: "Ship. Test. Deploy. Repeat.",
      label: "Text",
    },
    axis: {
      type: "select",
      default: "x",
      options: ["x", "y"],
      label: "Axis",
    },
    entryOffset: {
      type: "number",
      default: 88,
      min: 8,
      max: 160,
      step: 1,
      label: "Entry offset",
    },
    gap: {
      type: "number",
      default: 10,
      min: 0,
      max: 48,
      step: 1,
      label: "Gap",
    },
    firstDuration: {
      type: "number",
      default: 10,
      min: 4,
      max: 30,
      step: 1,
      label: "First duration",
    },
    pushDuration: {
      type: "number",
      default: 13,
      min: 4,
      max: 30,
      step: 1,
      label: "Push duration",
    },
    entryScale: {
      type: "number",
      default: 0.992,
      min: 0.9,
      max: 1,
      step: 0.001,
      label: "Entry scale",
    },
    entryBlur: {
      type: "number",
      default: 3.5,
      min: 0,
      max: 10,
      step: 0.1,
      label: "Entry blur",
    },
    reflowBlur: {
      type: "number",
      default: 0.8,
      min: 0,
      max: 4,
      step: 0.1,
      label: "Reflow blur",
    },
    fontSize: {
      type: "number",
      default: 72,
      min: 12,
      max: 160,
      step: 1,
      label: "Font size",
    },
    color: { type: "color", default: "#101828", label: "Color" },
    fontWeight: {
      type: "select",
      default: "600",
      options: FONT_WEIGHT_OPTIONS,
      label: "Font weight",
    },
    fontFamily: FONT_FAMILY_CONTROL,
  },
  durationInFrames: 75,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#FAFAFA" },
};
